"""post.initial

Revision ID: 01a41ca6e47a
Revises: d8665da6208c
Create Date: 2026-01-29 16:26:40.738729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a41ca6e47a'
down_revision: Union[str, None] = 'd8665da6208c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administraciones', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('administraciones', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('administraciones_titulares', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('administraciones_titulares', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('agencias_inmobiliarias', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('agencias_inmobiliarias', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('colegios_profesionales', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('colegios_profesionales', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('diocesis', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('diocesis', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('entidades_religiosas', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('entidades_religiosas', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('notarias', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('notarias', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('privados', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('privados', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('registros_propiedad', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('registros_propiedad', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('tecnicos', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    op.alter_column('tecnicos', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True,
               schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tecnicos', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('tecnicos', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('registros_propiedad', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('registros_propiedad', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('privados', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('privados', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('notarias', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('notarias', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('entidades_religiosas', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('entidades_religiosas', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('diocesis', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('diocesis', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('colegios_profesionales', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('colegios_profesionales', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('agencias_inmobiliarias', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('agencias_inmobiliarias', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('administraciones_titulares', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('administraciones_titulares', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('administraciones', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    op.alter_column('administraciones', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True,
               schema='app')
    # ### end Alembic commands ###
