"""post.initial

Revision ID: 8deeb3920a68
Revises: 01a41ca6e47a
Create Date: 2026-01-29 17:36:15.349248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8deeb3920a68'
down_revision: Union[str, None] = '01a41ca6e47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administraciones', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.alter_column('administraciones', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'administraciones', 'tipos_via', ['tipo_via_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'administraciones', 'administraciones', ['administracion_padre_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'administraciones', 'municipios', ['municipio_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'administraciones', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'administraciones', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'administraciones', 'provincias', ['provincia_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'administraciones', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'administraciones', 'comunidades_autonomas', ['comunidad_autonoma_id'], ['id'], source_schema='app', referent_schema='app')
    op.alter_column('administraciones_titulares', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.alter_column('administraciones_titulares', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'administraciones_titulares', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'administraciones_titulares', 'provincias', ['provincia_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'administraciones_titulares', 'administraciones', ['administracion_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'administraciones_titulares', 'tipos_via', ['tipo_via_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'administraciones_titulares', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'administraciones_titulares', 'municipios', ['municipio_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'administraciones_titulares', 'comunidades_autonomas', ['comunidad_autonoma_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'administraciones_titulares', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.alter_column('agencias_inmobiliarias', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.alter_column('agencias_inmobiliarias', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'agencias_inmobiliarias', 'comunidades_autonomas', ['comunidad_autonoma_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'agencias_inmobiliarias', 'provincias', ['provincia_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'agencias_inmobiliarias', 'municipios', ['municipio_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'agencias_inmobiliarias', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'agencias_inmobiliarias', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'agencias_inmobiliarias', 'tipos_via', ['tipo_via_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'agencias_inmobiliarias', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'citas_bibliograficas', 'fuentes_historiograficas', ['fuente_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'citas_bibliograficas', 'inmuebles', ['inmueble_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'citas_bibliograficas', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'citas_bibliograficas', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'citas_bibliograficas', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.alter_column('colegios_profesionales', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.alter_column('colegios_profesionales', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'colegios_profesionales', 'tipos_via', ['tipo_via_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'colegios_profesionales', 'municipios', ['municipio_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'colegios_profesionales', 'comunidades_autonomas', ['comunidad_autonoma_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'colegios_profesionales', 'provincias', ['provincia_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'colegios_profesionales', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'colegios_profesionales', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'colegios_profesionales', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'comunidades_autonomas', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'comunidades_autonomas', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'comunidades_autonomas', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.alter_column('diocesis', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.alter_column('diocesis', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'diocesis', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'diocesis', 'tipos_via', ['tipo_via_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'diocesis', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'diocesis', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'diocesis', 'comunidades_autonomas', ['comunidad_autonoma_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'diocesis', 'municipios', ['municipio_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'diocesis', 'provincias', ['provincia_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'diocesis_titulares', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'diocesis_titulares', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'diocesis_titulares', 'diocesis', ['diocesis_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'diocesis_titulares', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'documentos', 'tipos_documento', ['tipo_documento_id'], ['id'], source_schema='app', referent_schema='app', ondelete='RESTRICT')
    op.create_foreign_key(None, 'documentos', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'documentos', 'tipos_licencia', ['tipo_licencia_id'], ['id'], source_schema='app', referent_schema='app', ondelete='RESTRICT')
    op.create_foreign_key(None, 'documentos', 'fuentes_documentales', ['fuente_documental_id'], ['id'], source_schema='app', referent_schema='app', ondelete='RESTRICT')
    op.create_foreign_key(None, 'documentos', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'documentos', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.alter_column('entidades_religiosas', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.alter_column('entidades_religiosas', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'entidades_religiosas', 'municipios', ['municipio_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'entidades_religiosas', 'tipos_entidad_religiosa', ['tipo_entidad_id'], ['id'], source_schema='app', referent_schema='app', ondelete='RESTRICT')
    op.create_foreign_key(None, 'entidades_religiosas', 'comunidades_autonomas', ['comunidad_autonoma_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'entidades_religiosas', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'entidades_religiosas', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'entidades_religiosas', 'provincias', ['provincia_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'entidades_religiosas', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'entidades_religiosas', 'tipos_via', ['tipo_via_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'entidades_religiosas_titulares', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'entidades_religiosas_titulares', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'entidades_religiosas_titulares', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'entidades_religiosas_titulares', 'entidades_religiosas', ['entidad_religiosa_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.create_foreign_key(None, 'estados_conservacion', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'estados_conservacion', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'estados_conservacion', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'estados_tratamiento', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'estados_tratamiento', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'estados_tratamiento', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'fuentes_documentales', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'fuentes_documentales', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'fuentes_documentales', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'fuentes_documentales', 'tipos_licencia', ['licencia_predeterminada_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'fuentes_historiograficas', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'fuentes_historiograficas', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'fuentes_historiograficas', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmatriculaciones', 'registros_propiedad', ['registro_propiedad_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmatriculaciones', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmatriculaciones', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmatriculaciones', 'inmuebles', ['inmueble_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmatriculaciones', 'tipos_certificacion_propiedad', ['tipo_certificacion_propiedad_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmatriculaciones', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles', 'comunidades_autonomas', ['comunidad_autonoma_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles', 'diocesis', ['diocesis_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles', 'estados_tratamiento', ['estado_tratamiento_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles', 'entidades_religiosas', ['entidad_religiosa_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles', 'inmuebles', ['inmueble_principal_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles', 'estados_conservacion', ['estado_conservacion_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles', 'municipios', ['municipio_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles', 'tipos_inmueble', ['tipo_inmueble_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles', 'provincias', ['provincia_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_denominaciones', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_denominaciones', 'inmuebles', ['inmueble_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_denominaciones', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_denominaciones', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_documentos', 'documentos', ['documento_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.create_foreign_key(None, 'inmuebles_documentos', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_documentos', 'inmuebles', ['inmueble_id'], ['id'], source_schema='app', referent_schema='app', ondelete='CASCADE')
    op.create_foreign_key(None, 'inmuebles_documentos', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_documentos', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_niveles_proteccion', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_niveles_proteccion', 'inmuebles', ['inmueble_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_niveles_proteccion', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_niveles_proteccion', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_niveles_proteccion', 'tipos_figura_proteccion', ['figura_proteccion_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_osm_ext', 'inmuebles', ['inmueble_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_osm_ext', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_osm_ext', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_osm_ext', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_usos', 'tipos_uso_inmueble', ['tipo_uso_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_usos', 'inmuebles', ['inmueble_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_usos', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_usos', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_usos', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_wd_ext', 'inmuebles', ['inmueble_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_wd_ext', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_wd_ext', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'inmuebles_wd_ext', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'intervenciones', 'inmuebles', ['inmueble_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'intervenciones', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'intervenciones', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'intervenciones', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'intervenciones_subvenciones', 'intervenciones', ['intervencion_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'intervenciones_subvenciones', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'intervenciones_subvenciones', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'intervenciones_subvenciones', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'intervenciones_tecnicos', 'roles_tecnico', ['rol_tecnico_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'intervenciones_tecnicos', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'intervenciones_tecnicos', 'intervenciones', ['intervencion_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'intervenciones_tecnicos', 'tecnicos', ['tecnico_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'intervenciones_tecnicos', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'intervenciones_tecnicos', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'municipios', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'municipios', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'municipios', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'municipios', 'provincias', ['provincia_id'], ['id'], source_schema='app', referent_schema='app')
    op.alter_column('notarias', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.alter_column('notarias', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'notarias', 'tipos_via', ['tipo_via_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'notarias', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'notarias', 'provincias', ['provincia_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'notarias', 'municipios', ['municipio_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'notarias', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'notarias', 'comunidades_autonomas', ['comunidad_autonoma_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'notarias', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'notarias_titulares', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'notarias_titulares', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'notarias_titulares', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'notarias_titulares', 'notarias', ['notaria_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'osm_places', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'osm_places', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'osm_places', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'portals_detecciones', 'inmuebles', ['inmueble_core_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'portals_detecciones', 'portals_inmuebles_raw', ['inmueble_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'portals_detecciones', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'portals_detecciones', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'portals_detecciones', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'portals_inmuebles_raw', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'portals_inmuebles_raw', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'portals_inmuebles_raw', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.alter_column('privados', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.alter_column('privados', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'privados', 'tipos_via', ['tipo_via_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'privados', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'privados', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'privados', 'provincias', ['provincia_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'privados', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'privados', 'comunidades_autonomas', ['comunidad_autonoma_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'privados', 'tipos_persona', ['tipo_persona_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'privados', 'municipios', ['municipio_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'provincias', 'comunidades_autonomas', ['comunidad_autonoma_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'provincias', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'provincias', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'provincias', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.alter_column('registros_propiedad', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.alter_column('registros_propiedad', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'registros_propiedad', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'registros_propiedad', 'municipios', ['municipio_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'registros_propiedad', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'registros_propiedad', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'registros_propiedad', 'provincias', ['provincia_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'registros_propiedad', 'tipos_via', ['tipo_via_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'registros_propiedad', 'comunidades_autonomas', ['comunidad_autonoma_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'registros_propiedad_titulares', 'registros_propiedad', ['registro_propiedad_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'registros_propiedad_titulares', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'registros_propiedad_titulares', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'registros_propiedad_titulares', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'roles', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'roles', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'roles', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'roles_tecnico', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'roles_tecnico', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'roles_tecnico', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'subvenciones_administraciones', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'subvenciones_administraciones', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'subvenciones_administraciones', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'subvenciones_administraciones', 'intervenciones_subvenciones', ['subvencion_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'subvenciones_administraciones', 'administraciones', ['administracion_id'], ['id'], source_schema='app', referent_schema='app')
    op.alter_column('tecnicos', 'latitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.alter_column('tecnicos', 'longitud',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'tecnicos', 'provincias', ['provincia_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tecnicos', 'tipos_via', ['tipo_via_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tecnicos', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tecnicos', 'comunidades_autonomas', ['comunidad_autonoma_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tecnicos', 'colegios_profesionales', ['colegio_profesional_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tecnicos', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tecnicos', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tecnicos', 'municipios', ['municipio_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tecnicos', 'roles_tecnico', ['rol_tecnico_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_certificacion_propiedad', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_certificacion_propiedad', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_certificacion_propiedad', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_documento', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_documento', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_documento', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_entidad_religiosa', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_entidad_religiosa', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_entidad_religiosa', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_figura_proteccion', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_figura_proteccion', 'comunidades_autonomas', ['comunidad_autonoma_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_figura_proteccion', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_figura_proteccion', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_inmueble', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_inmueble', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_inmueble', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_licencia', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_licencia', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_licencia', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_mime_documento', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_mime_documento', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_mime_documento', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_persona', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_persona', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_persona', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_titulo_propiedad', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_titulo_propiedad', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_titulo_propiedad', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_transmision', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_transmision', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_transmision', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_uso_inmueble', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_uso_inmueble', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_uso_inmueble', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_via', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_via', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'tipos_via', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'transmision_anunciantes', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'transmision_anunciantes', 'transmisiones', ['transmision_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'transmision_anunciantes', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'transmision_anunciantes', 'agencias_inmobiliarias', ['agencia_inmobiliaria_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'transmision_anunciantes', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'transmisiones', 'tipos_certificacion_propiedad', ['tipo_certificacion_propiedad_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'transmisiones', 'notarias', ['notaria_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'transmisiones', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'transmisiones', 'inmuebles', ['inmueble_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'transmisiones', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'transmisiones', 'registros_propiedad', ['registro_propiedad_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'transmisiones', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'transmisiones', 'tipos_transmision', ['tipo_transmision_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'usuario_rol', 'usuarios', ['usuario_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'usuario_rol', 'roles', ['rol_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'usuario_rol', 'usuarios', ['asignado_por'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'usuarios', 'usuarios', ['updated_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'usuarios', 'usuarios', ['created_by_id'], ['id'], source_schema='app', referent_schema='app')
    op.create_foreign_key(None, 'usuarios', 'usuarios', ['deleted_by_id'], ['id'], source_schema='app', referent_schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'usuarios', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'usuarios', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'usuario_rol', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'usuario_rol', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'usuario_rol', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'transmisiones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'transmisiones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'transmisiones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'transmisiones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'transmisiones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'transmisiones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'transmisiones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'transmisiones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'transmision_anunciantes', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'transmision_anunciantes', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'transmision_anunciantes', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'transmision_anunciantes', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'transmision_anunciantes', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_via', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_via', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_via', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_uso_inmueble', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_uso_inmueble', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_uso_inmueble', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_transmision', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_transmision', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_transmision', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_titulo_propiedad', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_titulo_propiedad', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_titulo_propiedad', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_persona', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_persona', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_persona', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_mime_documento', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_mime_documento', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_mime_documento', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_licencia', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_licencia', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_licencia', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_inmueble', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_inmueble', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_inmueble', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_figura_proteccion', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_figura_proteccion', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_figura_proteccion', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_figura_proteccion', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_entidad_religiosa', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_entidad_religiosa', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_entidad_religiosa', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_documento', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_documento', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_documento', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_certificacion_propiedad', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_certificacion_propiedad', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tipos_certificacion_propiedad', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tecnicos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tecnicos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tecnicos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tecnicos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tecnicos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tecnicos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tecnicos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tecnicos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'tecnicos', schema='app', type_='foreignkey')
    op.alter_column('tecnicos', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('tecnicos', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'subvenciones_administraciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'subvenciones_administraciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'subvenciones_administraciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'subvenciones_administraciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'subvenciones_administraciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'roles_tecnico', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'roles_tecnico', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'roles_tecnico', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'roles', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'roles', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'roles', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'registros_propiedad_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'registros_propiedad_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'registros_propiedad_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'registros_propiedad_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'registros_propiedad', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'registros_propiedad', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'registros_propiedad', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'registros_propiedad', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'registros_propiedad', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'registros_propiedad', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'registros_propiedad', schema='app', type_='foreignkey')
    op.alter_column('registros_propiedad', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('registros_propiedad', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'provincias', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'provincias', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'provincias', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'provincias', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'privados', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'privados', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'privados', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'privados', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'privados', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'privados', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'privados', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'privados', schema='app', type_='foreignkey')
    op.alter_column('privados', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('privados', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'portals_inmuebles_raw', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'portals_inmuebles_raw', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'portals_inmuebles_raw', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'portals_detecciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'portals_detecciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'portals_detecciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'portals_detecciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'portals_detecciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'osm_places', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'osm_places', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'osm_places', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'notarias_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'notarias_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'notarias_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'notarias_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'notarias', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'notarias', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'notarias', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'notarias', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'notarias', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'notarias', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'notarias', schema='app', type_='foreignkey')
    op.alter_column('notarias', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('notarias', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'municipios', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'municipios', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'municipios', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'municipios', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'intervenciones_tecnicos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'intervenciones_tecnicos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'intervenciones_tecnicos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'intervenciones_tecnicos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'intervenciones_tecnicos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'intervenciones_tecnicos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'intervenciones_subvenciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'intervenciones_subvenciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'intervenciones_subvenciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'intervenciones_subvenciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'intervenciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'intervenciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'intervenciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'intervenciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_wd_ext', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_wd_ext', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_wd_ext', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_wd_ext', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_usos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_usos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_usos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_usos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_usos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_osm_ext', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_osm_ext', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_osm_ext', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_osm_ext', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_niveles_proteccion', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_niveles_proteccion', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_niveles_proteccion', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_niveles_proteccion', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_niveles_proteccion', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_documentos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_documentos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_documentos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_documentos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_documentos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_denominaciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_denominaciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_denominaciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles_denominaciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmuebles', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmatriculaciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmatriculaciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmatriculaciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmatriculaciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmatriculaciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'inmatriculaciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'fuentes_historiograficas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'fuentes_historiograficas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'fuentes_historiograficas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'fuentes_documentales', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'fuentes_documentales', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'fuentes_documentales', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'fuentes_documentales', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'estados_tratamiento', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'estados_tratamiento', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'estados_tratamiento', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'estados_conservacion', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'estados_conservacion', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'estados_conservacion', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'entidades_religiosas_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'entidades_religiosas_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'entidades_religiosas_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'entidades_religiosas_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'entidades_religiosas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'entidades_religiosas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'entidades_religiosas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'entidades_religiosas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'entidades_religiosas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'entidades_religiosas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'entidades_religiosas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'entidades_religiosas', schema='app', type_='foreignkey')
    op.alter_column('entidades_religiosas', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('entidades_religiosas', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'documentos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'documentos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'documentos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'documentos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'documentos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'documentos', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'diocesis_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'diocesis_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'diocesis_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'diocesis_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'diocesis', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'diocesis', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'diocesis', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'diocesis', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'diocesis', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'diocesis', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'diocesis', schema='app', type_='foreignkey')
    op.alter_column('diocesis', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('diocesis', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'comunidades_autonomas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'comunidades_autonomas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'comunidades_autonomas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'colegios_profesionales', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'colegios_profesionales', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'colegios_profesionales', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'colegios_profesionales', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'colegios_profesionales', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'colegios_profesionales', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'colegios_profesionales', schema='app', type_='foreignkey')
    op.alter_column('colegios_profesionales', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('colegios_profesionales', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'citas_bibliograficas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'citas_bibliograficas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'citas_bibliograficas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'citas_bibliograficas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'citas_bibliograficas', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'agencias_inmobiliarias', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'agencias_inmobiliarias', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'agencias_inmobiliarias', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'agencias_inmobiliarias', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'agencias_inmobiliarias', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'agencias_inmobiliarias', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'agencias_inmobiliarias', schema='app', type_='foreignkey')
    op.alter_column('agencias_inmobiliarias', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('agencias_inmobiliarias', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'administraciones_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'administraciones_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'administraciones_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'administraciones_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'administraciones_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'administraciones_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'administraciones_titulares', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'administraciones_titulares', schema='app', type_='foreignkey')
    op.alter_column('administraciones_titulares', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('administraciones_titulares', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'administraciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'administraciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'administraciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'administraciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'administraciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'administraciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'administraciones', schema='app', type_='foreignkey')
    op.drop_constraint(None, 'administraciones', schema='app', type_='foreignkey')
    op.alter_column('administraciones', 'longitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('administraciones', 'latitud',
               existing_type=sa.Float(precision=10, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
